// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID          int32          `db:"id" json:"id"`
	UserID      int32          `db:"user_id" json:"user_id"`
	OrderDate   pgtype.Date    `db:"order_date" json:"order_date"`
	TotalAmount pgtype.Numeric `db:"total_amount" json:"total_amount"`
}

type Orderproduct struct {
	OrderID   int32 `db:"order_id" json:"order_id"`
	ProductID int32 `db:"product_id" json:"product_id"`
	Quantity  int32 `db:"quantity" json:"quantity"`
}

type Product struct {
	ID          int32          `db:"id" json:"id"`
	ProductName string         `db:"product_name" json:"product_name"`
	Price       pgtype.Numeric `db:"price" json:"price"`
}

type User struct {
	ID       int32  `db:"id" json:"id"`
	Username string `db:"username" json:"username"`
	Email    string `db:"email" json:"email"`
	Password string `db:"password" json:"password"`
}
