// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	DeleteOrder(ctx context.Context, id int32) error
	DeleteProduct(ctx context.Context, price pgtype.Numeric) error
	DeleteUserByID(ctx context.Context, id int32) error
	GetAllProducts(ctx context.Context) ([]*Product, error)
	GetAllUsers(ctx context.Context) ([]*GetAllUsersRow, error)
	GetOrdersByUser(ctx context.Context, userID int32) ([]*GetOrdersByUserRow, error)
	GetUserByUsername(ctx context.Context, username string) (*GetUserByUsernameRow, error)
	InsertOrder(ctx context.Context, arg InsertOrderParams) error
	InsertOrderProduct(ctx context.Context, arg InsertOrderProductParams) error
	InsertProduct(ctx context.Context, arg InsertProductParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) error
}

var _ Querier = (*Queries)(nil)
